name: .NET Build and Save DLL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Test project
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Upload compiled DLL
        uses: actions/upload-artifact@v4
        with:
          name: compiled-class-library
          path: '**/bin/Release/**/*.dll'
